### ISSUE TITLE
Corrigir o comando !pergunta

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#11]
O comando [`!pergunta`](https://github.com/levxyca/pandadomalbot/blob/main/commands/pergunta.js) está sendo disparado em casos que não fazem sentido. Por ter somente uma verificação se a string existe na mensagem, qualquer mensagem que tenha essa sequência (`!pergunta`) irá disparar a resposta do bot:

<kbd>![pergunta-no-meio-de-frases](https://user-images.githubusercontent.com/3982052/95915935-49cacd00-0d7e-11eb-818d-71e024654cdc.png)</kbd>

Também não existe uma verificação se algo foi perguntado, assim, enviar somente `!pergunta` (sem nada escrito depois) também irá disparar uma resposta do bot:

<kbd>![pergunta-sem-pergunta](https://user-images.githubusercontent.com/3982052/95916012-6e26a980-0d7e-11eb-9fb4-689e2740339d.png)</kbd>

### TODO
- Responder ao comando somente se a mensagem iniciar com `!pergunta` e tiver algo escrito após o comando. Ex: `!pergunta a levxyca some aos finais de semana?`

**Comment by londarks** [comment]
Você poderia pegar toda a string do inputs do usuário e colocar ela em um array, e verificar se no primeiro índice tem o valor que você deseja `!pergunta` caso for verdadeira, você executa o resto do comando.! 
um exemplo de como pensei.
```
const a = '!pergunta';
const b = '!pergunta terra e plana?';

const arr = b.split(' ');
	
if (arr.indexOf(a) != -1) {
  console.log('verdade');
}
```

**Comment by rn4n** [comment]
Yep, pode usar [`Array#includes()`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/contains) _(que é um pouco mais moderno)_ nessa verificação de array, ao invés do `indexOf`:

```js
if (arr.includes(a)) {
   // ...
}
```

Tem a função [`String#startsWith()`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) também.

Manda um pr @londarks .
