### ISSUE TITLE
Corrigir o comando !ban

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#12]
[Esse comando](https://github.com/levxyca/pandadomalbot/blob/main/commands/ban.js) está sendo disparado em qualquer mensagem que tenha `!ban`, independente de ser no começo/meio da mensagem:

<kbd>![comando-ban](https://user-images.githubusercontent.com/3982052/95920411-c7dea200-0d85-11eb-89c6-cf495a92368d.png)</kbd>

Com isso, nem sempre ele pega o usuário corretamente pois está sendo obtida a posição `1` do array após o split. Ex:

<kbd>![false-username](https://user-images.githubusercontent.com/3982052/95920471-e04ebc80-0d85-11eb-9f18-b6771a79392a.png)</kbd>

### TODO

- O bot deve responder somente quando a mensagem for iniciada com `!ban` e tiver algum usuário mencionado.
Ex: `!ban @jubileu`.

**Comment by carlosfrodrigues** [comment]
Oi! Eu gostaria de pegar essa issue, você pode dar assign dela pra mim? :)

**Comment by levxyca** [comment]
> Oi! Eu gostaria de pegar essa issue, você pode dar assign dela pra mim? :)

Prontinho! ^^
