### ISSUE TITLE
!apostaLev

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#128]
Hoje em dia no canal existe o `!lev` que gera uma levxyca aleatória para a pessoa do chat.
![image](https://user-images.githubusercontent.com/19956731/109164068-c2905b80-7758-11eb-90bf-c01fa9e9f934.png)
A ideia é que seja criado um comando que vai ser chamado de `!apostaLev` onde a pessoa vai digitar no chat, por exemplo, `!apostaLev delévs` e caso a sua aposta seja igual ao nome que saiu no gerador, ela ganhará 150 pontos.

**Comment by rn4n** [comment]
Vi que esse comando usa o arquivo `gerador-de-levs`. Tem como dar um exemplo do que tem nesse arquivo?

**Comment by levxyca** [comment]
claro 😊 o arquivo tem a seguinte estrutura:

```
[
  {
    "cod": "levestica"
  },
  {
    "cod": "Levxícara"
  },
  {
    "cod": "levchica"
  }
]
```
