### ISSUE TITLE
Tornar a quantidade de !irritar configurável via variável de ambiente

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#130]
A quantidade máxima de uso do `!irritar` está _hardcoded_ [neste arquivo](https://github.com/levxyca/pandadomalbot/blob/main/commands/jail/commands/irritar.js#L11). A ideia é tornar esse valor configurável via variável de ambiente, semelhante ao que foi feito [nessa abordagem](https://github.com/levxyca/pandadomalbot/blob/99acebaf0176f3fc76e226a6674253e6648fd482/commands/carinho.js#L5-L6).  Exemplo:

```ini
# .env
MAXIMO_DE_IRRITAR_DIARIOS=10
```

**Comment by levxyca** [comment]
Resolvi isso [nesse](https://github.com/levxyca/pandadomalbot/commit/c82ec7a19070170cf8ccb4bbdc15e1f6091207e1) commit. Vou fechar a issue.
