### ISSUE TITLE
Adicionar emote PunOko nas respostas do bot

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#132]
Nas mensagens relacionadas a prisão, adicionar o emote `PunOko` antes das frases. Exemplo ([salvar.js](https://github.com/levxyca/pandadomalbot/blob/main/commands/jail/commands/salvar.js#L15)):

```diff
- client.say(target, `/me ${context.username}, você já tentou se salvar.`);
```

```diff
+ client.say(target, `/me PunOko ${context.username}, você já tentou se salvar.`);
```

**Comment by levxyca** [comment]
Adicionei o emote nas respostas que já tinham antes, vou fechar essa issue.
