### ISSUE TITLE
Timer de Eitas!

### ISSUE THREAD

**Issue by AndreBezBirolo** [levxyca/pandadomalbot#150]
Fazer um contador na live de quanto tempo a Levxyca consegue ficar sem falar eita. Quando o comando !eita for utilizado zerar o timer.

**Comment by rn4n** [comment]
Talvez fique estranho o bot mandar duas mensagens em sequência, uma do contador e outra dizendo quando foi a última vez que falou "eita", ex:

```
@rnan: !eita
@bot: @levxyca já disse eita 1 vez hoje e 1111 vezes desde o dia 09/10/2020
@bot: A última vez que @levxyca disse eita foi há 2 minutos
@jubileu: !eita
@bot: @levxyca já disse eita 2 vezes hoje e 1112 vezes desde o dia 09/10/2020
@bot: A última vez que @levxyca disse eita foi há 4 minutos
...
```

@levxyca essa issue ainda vai ser feita? Se for, vai ser esse comportamento mesmo?

**Comment by levxyca** [comment]
@rn4n acredito que não faça mais sentido fazer essa issue, ainda mais que atualmente o pessoal usa mais os comandos da prisão e os contadores bem raramente.
