### ISSUE TITLE
Comandos Simples ⭐

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#180]
# Pensando no refatoramento dos comandos simples do 'pandadomalbot'

Um comando simples do bot, seria um comando onde ele apenas responde uma mensagem simples pré-definida.

> Segue uma imagem de exemplo de um comando simples do bot.

![comando_simples](https://user-images.githubusercontent.com/19956731/138162419-af5b0324-e67f-4a6f-8c2b-5953dbe0dbf3.png)

## O que precisa ser melhorado aqui?

Foi apontado a questão referente ao ```exports.default = (client, target, context, message)``` pois em todos os arquivos relacionados aos comandos sempre passamos esses mesmos parâmetros.

Visto que é sempre a mesma coisa, seria interessante pensar em uma forma de melhorar isso para não fica precisando replicar este código repetidamente.

**Comment by rn4n** [comment]
@levxyca essa issue foi resolvida?
Agora é possível responder com uma string diretamente, sem a necessidade de implementar uma função.

https://github.com/levxyca/pandadomalbot/blob/9574e4935b01c8887a0ecfd188cfb8e3270d77c7/src/commands/misc/tema.js#L1-L6

**Comment by levxyca** [comment]
@rn4n essa issue está super resolvida!!!
