### ISSUE TITLE
Criar um objeto pessoa ╰(*°▽°*)╯

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#181]
# Criar um JSON único para armazenar as 'pessoas'

A ideia é unificar os vários arquivos JSON que existem e são necessários para o funcionamento do 'pandadomalbot'.

![image](https://user-images.githubusercontent.com/19956731/138165596-7474ffbe-1f86-4577-acd1-be5696ddf51a.png)

Nesse caso, temos uma pasta chama *data* onde é colocado todos os arquivos JSON referentes aos armazenamentos de dados do bot. O pensamento é de juntar em um objeto só os dados referentes a uma pessoa.

Por exemplo:

Vamos partir do seguinte ponto, o que uma pessoa tem?

- Nome
- Quantidade de carinhos
- Quantidade de irritar
- Quantidade de pontos

**Comment by rn4n** [comment]
@levxyca como ficaria "carinhos" e "irritar" em inglês? 😅

O irritar pode virar um `person.counter.irritations` (sendo um `Number`) mas o carinho não sei como chamar. Sugestões?

**Comment by levxyca** [comment]
@rn4n Talvez o carinho poderia virar um **affections**?
