### ISSUE TITLE
Manipulando arquivos JSON

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#182]
# Manipulando os arquivos JSON de uma melhor forma

Um problema atual e crítico do 'pandadomalbot' 🐼 é referente a leitura e escrita de dados nos arquivos em formato JSON. Atualmente, o bot, em todos os seus comandos e funcionalidades, lê o arquivo e escreve nele toda vez que um comando aciona um mudança nos dados de algum arquivo.

Isso acaba nos gerando muitos problemas ao rodar o bot durante uma live com muitas pessoas usando os comandos simultaneamente, dando uma "sobrecarga" no bot.

Segue uma imagem de exemplo de como está funcionando atualmente:

![image](https://user-images.githubusercontent.com/19956731/138189547-e94c8322-6d18-4712-86ee-623fd9b4b6bf.png)

> Os `readDataJSON` e `writeDataJSON` são as linhas de código referente á essa manipulação de dados nos arquivos.

## Como melhorar isso então?

Uma ideia que foi passada, é, no lugar de usar os `readDataJSON` e `writeDataJSON` TODA vez que precisamos manipular esses arquivos, ter variáveis que armazenam esses dados, fazendo uma leitura e escrita nos arquivos apenas ao iniciar o bot.

**Comment by rn4n** [comment]
A ideia de ler o arquivo na inicialização do bot e fazer as mudanças no objeto em memória é uma boa. Só precisaríamos de alguma implementação que garanta que quando o bot for finalizado (com sucesso ou não), o conteúdo em memória seja persistido no arquivo. Não manjo como fazer isso em Node, nunca li a respeito. 😅

Mas até com os dados em memória pode acontecer de dar problema, dependendo de como estão as implementações dos comandos. Um comando pode estar subtraindo os pontos de alguém enquanto outro está somando, dependendo de quando objeto for acessado.

Talvez (talvez!) dá para atacar esse problema usando algum tipo de processamento de fila. Por exemplo, os comandos `!somarpontos` e `!subtrairpontos` não vão atualizar esse valor no momento em que foram chamados, na real eles vão criar uma tarefa (de somar ou subtrair) que será adicionada em uma lista e processada uma a uma posteriormente.

Esse "posteriormente" pode ocorrer quase que instantaneamente ou pode demorar um pouco, dependendo da quantidade de tarefas na fila.

**Comment by rn4n** [comment]
Toparia refatorar boa parte do bot? 😏 @levxyca

**Comment by levxyca** [comment]
Eu estou querendo refatorar o bot faz um tempo mas me falta conhecimento e tempo @rn4n kkkkkkkkk se topar podemos ir fazendo ao poucos!

**Comment by rn4n** [comment]
@levxyca bóra.
Só dar as direções do que quer fazer com o bot.

**Comment by levxyca** [comment]
Simbora entãaaaaaao @rn4n !!!
Acho que podemos começar com o que já temos, como essa issue aqui Kappa A ideia é ir refatorando conforme ir analisando o código e sentindo necessidade. No caso, essa é uma issue que afeta bastante o panda né!

**Comment by rn4n** [comment]
Vou tentar resolver esse problema.

**Comment by rn4n** [comment]
Eu acho que resolver a #181 facilitaria o trabalho nessa issue. 👀
