### ISSUE TITLE
Dar pontos para usuário que der sub de presente

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#193]
Por meio do evento [`subgift`][1], é possível obter algumas informações sobre um sub de presente dado a um telespectador do canal.
A ideia dessa issue é dar pontos extras para o usuário que der subs de presente 😄.

**PS**: discutir com a @levxyca a quantidade de pontos a ser dada.

[1]:https://github.com/tmijs/docs/blob/gh-pages/_posts/v1.4.2/2019-03-03-Events.md#subgift

**Comment by rn4n** [comment]
@levxyca quantos pontos?

**Comment by levxyca** [comment]
@rn4n 100 pontos.
