### ISSUE TITLE
Criar comando !pergunta

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#2]
Criar um comando que quando alguém pergunta algo o bot responde com: sim, não, provavelmente, com certeza.

Exemplo: 
Levxyca manda:
!pergunta eu sou linda

Resposta:
Não, @levxyca.

**Comment by Wendlereis** [comment]
Olá! Curti essa issue, poderia atribuir para mim?

Apenas uma dúvida, as respostas são aleatórias, certo?
