### ISSUE TITLE
pergunta

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#208]
Mover o comando `!pergunta` para a nova estrutura.

https://github.com/levxyca/pandadomalbot/blob/691955bac7ca6d263e384f65271e7b5ef4f76875/src/commands/pergunta.js#L1-L61

**Comment by jbeanz** [comment]
Hola, hablas ingles? puedo ayudarte pero hablo espanol un poquito.

**Comment by levxyca** [comment]
Hi @jbeanz! We can communicate in English, however, the construction of this project is in Portuguese.
