### ISSUE TITLE
piada

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#209]
Mover o comando `!piada` para a nova estrutura:

https://github.com/levxyca/pandadomalbot/blob/691955bac7ca6d263e384f65271e7b5ef4f76875/src/commands/piada.js#L1-L20

**Comment by rn4n** [comment]
@levxyca pode colocar um exemplo de conteúdo do arquivo "piadas.json"?

**Comment by levxyca** [comment]
@rn4n atualmente o arquivo de "piadas.json" segue essa estrutura:
```
[
  {
    "pergunta": "O que o pato falou para a pata?",
    "resposta": "Vem quá"
  }
]
```
