### ISSUE TITLE
ensinamento

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#210]
Mover o comando `!ensinamento` para a nova estrutura:

https://github.com/levxyca/pandadomalbot/blob/main/src/commands/ensinamento.js#L1-L14

**Comment by rn4n** [comment]
@levxyca pode colocar um exemplo de conteúdo do arquivo "ensinamentos.json"?

**Comment by levxyca** [comment]
@rn4n estrutura do arquivo "ensinamentos.json":
```
[
 {
  "ensinamento": "Chega de procrastinar e vamos cochilar."
 }
]
```
