### ISSUE TITLE
Concertar o que o bot fala quando fica on

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#22]
O bot deveria estar mandando a seguinte frase assim que ele é rodado e fica online mas ele está mandando apenas após alguém enviar a primeira mensagem no chat.
"Estou de olho em vocês.

**Comment by rn4n** [comment]
Eu posso fazer.

**Comment by rn4n** [comment]
@levxyca tem outros erros no bot, vou tentar mandar um PR corrigindo antes e depois faço essa issue.

**Comment by levxyca** [comment]
> @levxyca tem outros erros no bot, vou tentar mandar um PR corrigindo antes e depois faço essa issue.

Tudo bem, tranquilo! Se quiser abrir alguma issue fica a vontade também.
