### ISSUE TITLE
Implementar prisão

### ISSUE THREAD

**Issue by rn4n** [levxyca/pandadomalbot#226]
Comandos a serem migrados para a nova estrutura:

- [x] escapar
- [x] presos/preso
- [x] proteger
- [x] protegido
- [x] salvar

E criar a função para prender os usuários (bloqueado pelo PR #228).

**Comment by rn4n** [comment]
@levxyca no caso de `!proteger`, e se ao invés de escolher um sub (de um arquivo .json), o bot escolher alguém online no chat naquele momento? Acho que funciona melhor, já que pode ser que o sub nem esteja online na live e vai estar protegido mesmo assim 🤡.

**Comment by levxyca** [comment]
@rn4n será que teria como fazer algo tipo, dentro dos subs, eles verificar quem está online no chat? Se não tiver, podemos trocar pra ser alguém online no chat sem ser sub mesmo, sem problemas.

**Comment by rn4n** [comment]
@levxyca dá pra fazer sim.
Como é o formato do arquivo que você tem subs? Pode postar um exemplo?

**Comment by levxyca** [comment]
@rn4n atualmente é só um ``txt`` com os subs um em cada linha la dentro.

![image](https://user-images.githubusercontent.com/19956731/152699278-bc8f341a-34b8-4b2e-893f-8bdfcdae0f8f.png)

**Comment by rn4n** [comment]
@levxyca pode ser um JSON para poder usar as funções que já existem?

https://github.com/levxyca/pandadomalbot/blob/818ed9d4cf4cb519c48d28d769b178615d3f23da/src/utilities/data-file.js#L17

```json
// Exemplo: subs.json
[
   "sub1",
   "sub2",
   "sub3"
  // ...
]
```

Se tiver que ser .txt não tem problema também.

**Comment by levxyca** [comment]
@rn4n pode ser sim!
