### ISSUE TITLE
Protegido do pandadomalbot

### ISSUE THREAD

**Issue by fsouza** [levxyca/pandadomalbot#24]
Nasceu como meme no PR #23, mas uma parada que poderíamos fazer é ter um sub "imbanível" por live.

No começo da live, o pandadomalbot escolheria um sub aleatório e esse sub ficaria protegido durante toda a live. Quem tentar dar ban nesse sub, sempre toma timeout.

Precisamos da lista de subs, que é meio chato de conseguir pela API da Twitch. Uma alternativa é manter a lista manualmente num arquivo local.

**Comment by adielseffrin** [comment]
E além da lista, tem que ver se tem como pegar o início da live, caso o bot fique hospedado rodando 24/7.
Pra poder randomizar o imbanível.
