### ISSUE TITLE
Rinha de famílias

### ISSUE THREAD

**Issue by fsouza** [levxyca/pandadomalbot#28]
No caso de !ban trocado entre família dev e família codes, faz o ban ser 50/50, sempre alguém seria banido.

**Comment by jpbrab0** [comment]
wow

**Comment by jpbrab0** [comment]
posso tentar fazer essa pr

**Comment by levxyca** [comment]
Seria interessante, além disso, ter uma mensagem personalizada, onde por exemplo, o bot identifica que a pessoa tem DEV ou CODES no nick e manda uma mensagem de acordo.
