### ISSUE TITLE
Subir o bot

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#29]
Subir o bot em algum lugar para não precisar roda na máquina toda vez que a streamer abre stream.

**Comment by londarks** [comment]
Se você tiver cartão de credito (mastercard) você consegue 2 vps (banco de dados incluso, e varias outras coisas) da Oracle de graça de 1GB de ram e e totalmente free e customizada caso, não queira você tem a opção de subir ele no Heroku porem ele tem uma "capacidade" máxima de requisição
