### ISSUE TITLE
TO quando irritar o bot

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#40]
O **panda do mal** tem um comando chamado _'!irritar'_ onde, quando a pessoa da esse comando no chat da twitch, tem uma **possibilidade** dela ser _"pega"_ pelo bot. No momento, o bot só apresenta uma mensagem dizendo que o panda pegou a pessoa, o que queremos é que além dessa mensagem, a pessoa _"pega"_ receba um **timout** no canal da twitch. Esse timout pode ser de um **valor curto** de no **máximo** até **30 segundos**.

https://github.com/levxyca/pandadomalbot/blob/8a6a37af20a7d3f80c432b48b44c94d242a16191/bot.js#L176
![image](https://user-images.githubusercontent.com/19956731/96586964-16c19580-12b8-11eb-8b8e-fbba2d22e9ac.png)

**Comment by adielseffrin** [comment]
Deixa pra mim então :D

**Comment by levxyca** [comment]
@adielseffrin Já testei e está funcionando, acabei de dar merge nele, sexta-feira já vai estar funcionando na live \o/
