### ISSUE TITLE
Pessoa que foi presa não pode conseguir salvar ela mesma

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#41]
O **panda do mal** tem um esquema onde, dentro de um intervalo de tempo, ele _"prende"_ alguma pessoa que esteja no chat e as outras pessoas podem tentar _"salvá-la"_ utilizando o _'!salvar'_, o problema que temos é que a pessoa _"presa"_ consegue dar _'!salvar'_ e se salvar da prisão do panda também. Nesse caso, queremos que quem for _"preso"_ **não** tenha possibilidade de se _"salvar"_ sozinho, outras pessoas terão de _"salvar"_ a pessoa.

https://github.com/levxyca/pandadomalbot/blob/8a6a37af20a7d3f80c432b48b44c94d242a16191/bot.js#L201

https://github.com/levxyca/pandadomalbot/blob/8a6a37af20a7d3f80c432b48b44c94d242a16191/bot.js#L154

**Comment by FelipeGrijo** [comment]
Posso fazer?

**Comment by levxyca** [comment]
@FelipeGrijo Fui testar o código e tive o seguinte erro quando a pessoa presa deu o _'!salvar'_:

![image](https://user-images.githubusercontent.com/19956731/96791635-2aabeb00-13cf-11eb-8275-a973808cbbc8.png)

**Comment by FelipeGrijo** [comment]
Esse erro foi causado por outro PR, tô procurando aqui.

**Comment by levxyca** [comment]
@FelipeGrijo foi isso mesmo que aconteceu! Já arrumei aqui, testei e está funcionando tudo certo! Já está dado merge na main e na próxima stream estará em funcionamento \o/ Parabéns pelo PR ^^
