### ISSUE TITLE
Criação de um sistema de pontos

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#42]
O **panda do mal** tem um esquema onde, dentro de um intervalo de tempo, ele _"prende"_ alguma pessoa que esteja no chat e as outras pessoas podem tentar _"salvá-la"_ utilizando o _'!salvar'_. Queremos implementar um **sistema de pontos**, onde, quem der '!salvar' e salvar a pessoa primeiro, ganharia por ex: 100 pontos. Esses pontos precisam ser **armazenados** em algum lugar e ter **fácil acesso**. No caso, queremos um sistema de pontos onde temos uma lista de usuários e podemos dar pontos de acordo com ações, como exemplo do '!salvar' ou manualmente.

**Comment by londarks** [comment]
Poderia armazenar em um json  se não for muito grande a quantidade de usuários caso for pode optar por um sqlite, no caso seria local e seria um pouco difícil de acessar mas poderia criar alguns comandos administrativo para o bot que poderia fazer o deletar alterar ou visualizar mesmo com base no Nome/Id da pessoa

[funcionamento]
Toda vez que alguém der o comando, ele verifica se o usuário existe, no banco de dados e caso não faz o cadastro, caso já exista, ele `salva` a pessoa pressa pelo bot  e adiciona os points
