### ISSUE TITLE
Site do panda do mal

### ISSUE THREAD

**Issue by KastroWalker** [levxyca/pandadomalbot#47]
Criar um comando `!help` ou `!site` para retornar o site do panda

exemplo

`deninhobot: !help`

`pandadomalbot: levxyca.github.io/pandadomalbot/`

**Comment by levxyca** [comment]
Essa eu faço Kappa

**Comment by levxyca** [comment]
Foi direto na main, mas como é algo simples e eu testei antes eu tenho fé em deninho.
