### ISSUE TITLE
criar comando !agua

### ISSUE THREAD

**Issue by tgxxx** [levxyca/pandadomalbot#66]
criar comando !agua fazendo assim toda vez que um membro digitar !agua o bot lembrar a levxyca de tomar agua durante a live!

**Comment by adielseffrin** [comment]
Mas se o bot lembrar, não acaba com a função da recompensa de hidratação?

**Comment by levxyca** [comment]
Sim, temos uma recompensa na loja do canal para comprar o hidratação, acho que talvez não faça muito sentido adicionar um comando assim no bot. Mas muito obrigada pela sugestão @tgxxx ^^
