### ISSUE TITLE
Integrar o bot com a API do twitter

### ISSUE THREAD

**Issue by adielseffrin** [levxyca/pandadomalbot#71]
Consumir a API do Twitter para buscar (ao menos) o tweet da live do dia.

**Comment by rn4n** [comment]
Como identificar o tweet da live do dia? Tem algum padrão?

**Comment by adielseffrin** [comment]
Dá pra fazer a pesquisa por "levxyca" e dai pegar a data atual no formato ano-mes-dia 00:00:00.000 e comparar com a hora do tweet, se a data do tweet for maior, é de hoje, dai compara se foi da conta da lev ("author_id") e tem que ver a source (<dados>['data']['source']), o streamlabs por exemplo é "Streamlabs Twitter". Ajudei?

**Comment by rn4n** [comment]
Referência: https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets

**Comment by rn4n** [comment]
@levxyca pode atribuir essa issue e a #72 pra mim.
Logo menos mando PR.

**Comment by rn4n** [comment]
@levxyca o que tem nesse arquivo `data/rt.txt`? Poderia mostrar o conteúdo dele?

**Comment by levxyca** [comment]
Temos um comando !addrt onde adicionamos uma mensagem com o link para o tweet do dia manualmente, no caso, o rt.txt armazena essa mensagem, por exemplo:
`!addrt teste`
Dentro do arquivo _data/rt.txt_ tem
`teste`

**Comment by rn4n** [comment]
E tem algum padrão essa mensagem? Eu já fiz a parte que pega o link e o tweet do dia, só preciso saber como responder o comando. Tipo `Ah, dá retweet aqui: {link}`.

**Comment by levxyca** [comment]
Pode colocar `Dá um RT aí por favorzinho levxycAnimada {link}`
