### ISSUE TITLE
Limitador de !irritar

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#90]
Colocar um limite onde o usuário só pode dar o !irritar 10 vezes por live.

**Comment by rn4n** [comment]
@levxyca pode me atribuir essa issue.

Quer que avise a pessoa que usou o comando que ela "atingiu o limite máximo"?
Ou quando usar `!irritar` depois de 10 vezes o bot simplesmente passa a ignorar?

Quanto a contagem, quer que salve isso em um arquivo ou pode ser em memória mesmo?
Em memória, o contador vai resetar sempre que reiniciar o bot.

**Comment by levxyca** [comment]
@rn4n pode colocar para avisar que atingiu o limite máximo. Eu penso em futuramente poder adicionar mais irritar para as pessoas por ações, por exemplo, 10 bits + 1 chance de irritar, de acordo com isso pode ver qual você acha melhor hahah

**Comment by rn4n** [comment]
Vou criar em memória inicialmente.
Depois, se houver necessidade, criamos uma issue para tratar isso.
