### ISSUE TITLE
Retirar o timeout caso a pessoa for salva

### ISSUE THREAD

**Issue by levxyca** [levxyca/pandadomalbot#98]
Caso alguém consiga salvar uma pessoa que esteja presa, fazer o panda dar untimout na pessoa salva.

**Comment by rn4n** [comment]
Hoje o timeout dado é bem baixo, mesmo que ninguém resgate a pessoa, ela volta a ter acesso ao chat bem rápido.
A ideia é dar um timeout alto e só deixar ela voltar a usar o chat quando alguém salvar?

**Comment by levxyca** [comment]
É, talvez hoje em dia não faça tanto sentido assim, quando criei essa issue acontecia da pessoa ser salva porém ficar um tempo sem falar no chat por causa do timeout, é que tem também o ponto que mesmo sendo bem rápido, por exemplo, 30 segundos de timout, as pessoas acabam salvando antes e aí me foi apontado criar essa issue.

**Comment by rn4n** [comment]
Se quiser, dá pra dar um `/untimeout [username]` quando salvar alguém. É bem simples.
Se quiser _assignar_ pra mim...
